# Generated by Django 3.1.2 on 2020-12-19 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_playlist2_playlist3'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.RenameModel(
            old_name='PlayList',
            new_name='PlayList5',
        ),
        migrations.RenameModel(
            old_name='PlayList2',
            new_name='PlayList6',
        ),
        migrations.RenameModel(
            old_name='PlayList1',
            new_name='PlayList7',
        ),
        migrations.DeleteModel(
            name='PlayList3',
        ),
        migrations.RemoveField(
            model_name='video',
            name='plist',
        ),
    ]
